[theme]
primaryColor = "#755800"   # Updated to requested color 
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"  # Prevent theme interference
textColor = "#111827"
font = "sans serif"

[browser]
gatherUsageStats = false